server:
  port: 6000
spring:
  application:
    name: crowd-order
  redis:
    host: 192.168.11.129
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka